#!/bin/bash

SRC_DIR=$PWD
IDX_DIR=/Users/gbelanger/Documents/active/I/integral/idx/

cd ../data/
getrevno
getrad
cd $IDX_DIR
./orbut2orbit
cd -
cp $IDX_DIR/orbit.dat .
cp $IDX_DIR/revno .
egrep '^[0-9]' $IDX_DIR/radiation_belt_passage.txt | sort > rad.dat

cd $SRC_DIR
