#! /bin/bash

cd ../results/current/

env_exit=`ls envelopeExit*.qdp`
pred_exit=`ls predictedExit*.qdp`
if [[ -f $env_exit ]] ; then
   echo "NO NO NO NO" >> $env_exit
   egrep '^[0-9]' $pred_exit >> $env_exit
   echo "HARD exit.ps/cps" >> $env_exit
   sed s/"Altitude (km)"/"Exit Altitude (km)"/g $env_exit > tmp
   mv tmp $env_exit
   qdp $env_exit
fi

env_entry=`ls envelopeEntry*.qdp`
pred_entry=`ls predictedEntry*.qdp`
if [[ -f $env_entry ]] ; then
   echo "NO NO NO NO" >> $env_entry
   egrep '^[0-9]' $pred_entry >> $env_entry
   echo "HARD entry.ps/cps" >> $env_entry
   sed s/"Altitude (km)"/"Entry Altitude (km)"/g $env_entry > tmp
   mv tmp $env_entry
   qdp $env_entry
fi
rm predicted*qdp

res=`ls residuals*qdp`
echo "HARD residuals.ps/cps" >> $res
qdp $res

#  Make PDF plots
for file in *.ps ; do epstopdf $file ; done

#  Make PNG plots
convert -density 200 exit.ps -flatten exit.png
convert -density 200 entry.ps -flatten entry.png
convert -density 200 residuals.ps -flatten residuals.png
