#!/bin/bash

##  Clean up previous results
cd ../results/current/
file=`ls residuals_*qdp`
if [[ $file != "" ]] ; then
    range=`echo $file | cut -d"_" -f2 | cut -d"." -f1`
    mkdir -p ../previous/$range
    content=`ls`
    if [[ $content != "" ]] ; then
	for file in $content ; do
	    mv $file ../previous/$range/
	done
    fi
fi
cd -

##  Get data files needed
#./getdatafiles

##  Calculate the predictions
javac *.java
java GetPerigeeHeights

##  Make the PS, PDF, and PNG plots
./makeplots
